# Generated by Django 2.0.1 on 2018-02-03 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timelineapp.lib.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, db_index=True, default=timelineapp.lib.utils.generate_uuid, editable=False, max_length=36, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Untitled', max_length=75)),
                ('date_of_event', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
